include:
  remote: https://raw.githubusercontent.com/elct9620/ruby-gitlab-ci/main/examples/containerize-rails.yml

variables:
  RUBY_VERSION: 3.1.0
  ASSETS_PRECOMPILE: 'yes'
  NODE_PACKAGE_REQUIRED: 'no'
