image: circleci/ruby:2.5-node-browsers

variables:
  RAILS_ENV: test
  POSTGRES_DB: rookie-works
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
  # NODE_VERSION: 8.0.0

stages:
  - verify
  - test

cache:
  paths:
    - vendor/ruby

rubocop:
  stage: verify
  before_script:
    - gem install rubocop -v 0.60.0
  script:
    - rubocop

brakeman:
  stage: verify
  before_script:
    - export LANG=C.UTF-8
    - export LC_ALL=C.UTF-8
    - gem install brakeman
  script:
    - brakeman

bundle-audit:
  stage: verify
  before_script:
    - export LANG=C.UTF-8
    - export LC_ALL=C.UTF-8
    - gem install bundler-audit
  script:
    - bundle audit

rspec:
  stage: test
  before_script:
    - bundle install --without development --path vendor
    - yarn install
    - bin/webpack
  services:
    - postgres:9.6
  script:
    - bundle exec rake db:migrate
    - bundle exec rspec --exclude-pattern spec/features/**/*_spec.rb

# Expose CI_MERGE_REQUEST variable
# https://gitlab.com/gitlab-org/gitlab-ce/issues/59689
review:
  stage: test
  before_script:
    - bundle install --without development --path vendor
    - yarn install
    - bin/webpack
  services:
    - postgres:9.6
  script:
    - bundle exec rake db:migrate
    - yarn run percy exec -- bundle exec rspec spec/features
  only:
    - merge_requests
