image: circleci/ruby:2.5-node-browsers

variables:
  RAILS_ENV: test
  POSTGRES_DB: rookie-works
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
  # NODE_VERSION: 8.0.0

stages:
  - verify
  - test

cache:
  paths:
    - vendor/ruby

rubocop:
  stage: verify
  before_script:
    - gem install rubocop -v 0.60.0
  script:
    - rubocop

brakeman:
  stage: verify
  before_script:
    - export LANG=C.UTF-8
    - export LC_ALL=C.UTF-8
    - gem install brakeman
  script:
    - brakeman

bundle-audit:
  stage: verify
  before_script:
    - export LANG=C.UTF-8
    - export LC_ALL=C.UTF-8
    - gem install bundler-audit
  script:
    - bundle audit

rspec:
  stage: test
  before_script:
    # - curl -SLO https://nodejs.org/dist/v$NODE_VERSION/node-v${NODE_VERSION}-linux-x64.tar.xz && tar -xJf node-v${NODE_VERSION}-linux-x64.tar.xz -C /usr/local --strip-components=1;
    - bundle install --without development --path vendor
    # - curl -o- -L https://yarnpkg.com/install.sh | bash
    # - export PATH=$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH
    - yarn install
    - bin/webpack
  services:
    - postgres:9.6
  script:
    - bundle exec rake db:migrate
    - bundle exec rspec --exclude-pattern spec/features/**/*_spec.rb

feature:
  stage: test
  before_script:
    # - curl -SLO https://nodejs.org/dist/v$NODE_VERSION/node-v${NODE_VERSION}-linux-x64.tar.xz && tar -xJf node-v${NODE_VERSION}-linux-x64.tar.xz -C /usr/local --strip-components=1;
    - bundle install --without development --path vendor
    # - curl -o- -L https://yarnpkg.com/install.sh | bash
    # - export PATH=$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH
    - yarn install
    - bin/webpack
    # - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    # - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
    # - apt-get update -yqqq
    # - apt-get install -y google-chrome-stable > /dev/null 2>&1
    # - sed -i 's/"$@"/--no-sandbox "$@"/g' /opt/google/chrome/google-chrome
    # - wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip
    # - unzip /tmp/chromedriver.zip chromedriver -d /usr/bin/
    # - rm /tmp/chromedriver.zip
    # - chmod ugo+rx /usr/bin/chromedriver
  services:
    - postgres:9.6
  script:
    - bundle exec rake db:migrate
    - yarn run percy exec -- bundle exec rspec spec/features
