image: ruby:2.5

variables:
  RAILS_ENV: test
  POSTGRES_DB: rookie-works
  NODE_VERSION: 8.0.0
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"

stages:
  - verify
  - test

cache:
  paths:
    - vendor/ruby

rubocop:
  stage: verify
  before_script:
    - gem install rubocop -v 0.60.0
  script:
    - rubocop

brakeman:
  stage: verify
  before_script:
    - export LANG=C.UTF-8
    - export LC_ALL=C.UTF-8
    - gem install brakeman
  script:
    - brakeman

bundle-audit:
  stage: verify
  before_script:
    - export LANG=C.UTF-8
    - export LC_ALL=C.UTF-8
    - gem install bundler-audit
  script:
    - bundle audit

rspec:
  stage: test
  before_script:
    - curl -SLO https://nodejs.org/dist/v$NODE_VERSION/node-v${NODE_VERSION}-linux-x64.tar.xz && tar -xJf node-v${NODE_VERSION}-linux-x64.tar.xz -C /usr/local --strip-components=1;
    - bundle install --without development --path vendor
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - yarn install
    - bin/webpack
  services:
    - postgres:9.6
  script:
    - bundle exec rake db:migrate
    - bundle exec rspec
