AllCops:
  TargetRubyVersion: 2.5.1
  DisplayCopNames: true
  Exclude:
    - bin/*
    - vendor/ruby/**/*
    - node_modules/**/*
    - db/schema.rb
Rails:
  Enabled: true
Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging
Metrics:
  Exclude:
    - db/migrate/*
    - Rakefile
    - Gemfile
    - config/**/*
    - spec/**/*
    - lib/tasks/**/*
Metrics/BlockLength:
  Exclude:
    - app/admin/*
    - lib/tasks/**/*
    - spec/**/*
    - config/**/*
Layout:
  Exclude:
    - config/environments/*
Style:
  Exclude:
    - spec/*_helper.rb
Style/BlockComments:
  Exclude:
    - config/**/*
    - spec/**/*
Style/Documentation:
  Enabled: false
