language: ruby
rvm:
  - 2.5.1
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
    - PGPORT=5433
    - DATABASE_URL=postgresql://postgres@localhost/rookie-works
before_script:
  - psql -c 'create database rookie-works;' -U postgres
