language: ruby
rvm:
  - 2.5.1
node_js: 8.0.0
addons:
  postgresql: 9.6
env:
  global:
    - RAILS_ENV=test
    - DATABASE_URL=postgresql://postgres@localhost/rookie
before_script:
  - psql -c 'create database rookie;' -U postgres
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - bin/webpack
script:
  - bundle exec rails db:migrate
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
