language: ruby
rvm:
  - 2.5.1
addons:
  postgresql: 9.6
env:
  global:
    - RAILS_ENV=test
    - DATABASE_URL=postgresql://postgres@localhost/rookie-works
before_script:
  - psql -c 'create database rookie-works;' -U postgres
script:
  - bundle exec rails db:migrate
  - bundle exec rspec
