# TODO: Replaced with GitHub Actions
language: ruby
rvm:
  - 3.1.0
cache:
  - bundler
  - yarn
addons:
  postgresql: 9.6
env:
  global:
    - RAILS_ENV=test
    - DATABASE_URL=postgresql://postgres@localhost/rookie
before_install:
  - nvm install 12
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
before_script:
  - psql -c 'create database rookie;' -U postgres
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rails db:migrate
  - bundle exec rspec --exclude-pattern spec/features/**/*_spec.rb
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
